import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { candidates, COUNTRIES, Destination, PostState } from '../domain/model';
import { C } from '../theme';
import { Icon } from './Artwork';

export function DestinationPicker({ state, value, onChange }: { state: PostState; value: Destination; onChange: (d: Destination) => void }) {
  const [search, setSearch] = useState('');
  const people = candidates(state);
  return <View style={s.wrap}><Text style={s.label}>Where should this hello go?</Text><View style={s.modes}>{([{ kind: 'anywhere', label: 'Surprise me', icon: 'shuffle' }, { kind: 'country', label: 'A country', icon: 'globe' }, { kind: 'person', label: 'An explorer', icon: 'passport' }] as const).map(mode => <Pressable accessibilityRole="radio" accessibilityState={{ checked: value.kind === mode.kind }} key={mode.kind} onPress={() => { setSearch(''); onChange(mode.kind === 'anywhere' ? { kind: 'anywhere' } : mode.kind === 'country' ? { kind: 'country', country: people[0]?.country || 'Japan' } : { kind: 'person', personId: people[0]?.id || '' }); }} style={[s.mode, value.kind === mode.kind && s.active]}><Icon name={mode.icon} size={18} color={value.kind === mode.kind ? '#fff' : C.green} /><Text style={[s.modeText, value.kind === mode.kind && { color: '#fff' }]}>{mode.label}</Text></Pressable>)}</View>{value.kind !== 'anywhere' && <><View style={s.search}><Icon name="search" size={17} /><TextInput accessibilityLabel={value.kind === 'country' ? 'Search countries' : 'Search explorers'} value={search} onChangeText={setSearch} placeholder={value.kind === 'country' ? 'Find a country…' : 'Find someone by name…'} placeholderTextColor={C.muted} style={s.input} /></View><View style={s.options}>{value.kind === 'country' ? COUNTRIES.filter(c => c.name.toLowerCase().includes(search.toLowerCase())).map(c => <Pressable key={c.name} accessibilityRole="radio" accessibilityState={{ checked: value.country === c.name }} onPress={() => onChange({ kind: 'country', country: c.name })} style={[s.option, value.country === c.name && s.chosen]}><Text style={s.optionText}>{c.flag} {c.name}</Text><Text style={s.count}>{people.filter(p => p.country === c.name).length} in your circle</Text></Pressable>) : people.filter(p => p.name.toLowerCase().includes(search.toLowerCase())).map(p => <Pressable key={p.id} accessibilityRole="radio" accessibilityState={{ checked: value.personId === p.id }} onPress={() => onChange({ kind: 'person', personId: p.id })} style={[s.option, value.personId === p.id && s.chosen]}><Text style={s.optionText}>{p.name}</Text><Text style={s.count}>{p.country}</Text></Pressable>)}</View>{value.kind === 'person' && !people.filter(p => p.name.toLowerCase().includes(search.toLowerCase())).length && <Text style={s.hint}>No matching explorer in your friendship circle.</Text>}{value.kind === 'country' && !COUNTRIES.some(c => c.name.toLowerCase().includes(search.toLowerCase())) && <Text style={s.hint}>That destination isn’t in this demo yet.</Text>}</>}<Text style={s.hint}>{value.kind === 'person' ? 'Only this explorer can receive your letter. If they pass, the journey ends.' : value.kind === 'country' ? 'Your courier stays in this country. If nobody else is available, the journey ends.' : 'Let shared interests guide your courier to someone in your friendship circle.'}</Text></View>;
}
const s = StyleSheet.create({
  wrap: { marginTop: 23, gap: 12 }, label: { fontSize: 12, fontWeight: '600', color: C.ink }, modes: { flexDirection: 'row', gap: 6 }, mode: { flex: 1, alignItems: 'center', gap: 7, paddingVertical: 13, backgroundColor: '#EAEEE2', borderRadius: 10 }, active: { backgroundColor: C.green }, modeText: { color: C.green, fontSize: 11 }, search: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', borderWidth: 1, borderColor: C.line, borderRadius: 9, paddingHorizontal: 12, gap: 9 }, input: { flex: 1, paddingVertical: 12, fontSize: 13, color: C.ink }, options: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, option: { paddingHorizontal: 12, paddingVertical: 10, borderWidth: 1, borderColor: C.line, backgroundColor: '#FCFCF8', borderRadius: 9, gap: 4 }, chosen: { borderColor: '#769573', backgroundColor: '#E4ECD9' }, optionText: { fontSize: 12, color: C.ink, fontWeight: '600' }, count: { fontSize: 10, color: C.muted }, hint: { fontSize: 11, lineHeight: 18, color: C.muted },
});
